### ISSUE TITLE
error: Declaration of Shortcode\Shortcode\AbstractShortcode::setShortcodeName(string $shortcodeName): 

### ISSUE THREAD

**Issue by james89321** [Daniel-KM/Omeka-S-module-Shortcode#1]
Hi,
I used a shortcode in site pages, and I get following error message.
Please help me with this error.

Fatal error: Declaration of Shortcode\Shortcode\AbstractShortcode::setShortcodeName(string $shortcodeName): Shortcode\Shortcode\AbstractShortcode must be compatible with Shortcode\Shortcode\ShortcodeInterface::setShortcodeName(string $shortcodeName): Shortcode\Shortcode\ShortcodeInterface in /home/web/omekas/modules/Shortcode/src/Shortcode/AbstractShortcode.php on line 7

- Sites > Pages > Pages Edit
- Add HTML Block
- Insert shortcode

I’ve tried the following shortcode.
`[items num=3 sort=created order=desc]`
`[items id=3]`
`[items site=1]`
`[count resource=items]`

System version
Omeka s v3.0.2
php 7.3

**Comment by Daniel-KM** [comment]
Thanks, it is fixed. It was related to the version of php.
